/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DesignRouteImport } from './routes/design'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedTabsRouteRouteImport } from './routes/_authenticated/_tabs/route'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedTabsEnquiriesRouteImport } from './routes/_authenticated/_tabs/enquiries'
import { Route as AuthenticatedTabsHomeRouteImport } from './routes/_authenticated/_tabs/home'
import { Route as AuthenticatedTabsInventoryRouteImport } from './routes/_authenticated/_tabs/inventory'
import { Route as AuthenticatedTabsSettingsRouteImport } from './routes/_authenticated/_tabs/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTabsRouteRoute = AuthenticatedTabsRouteRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTabsEnquiriesRoute =
  AuthenticatedTabsEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedTabsRouteRoute,
  } as any)
const AuthenticatedTabsHomeRoute = AuthenticatedTabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedTabsRouteRoute,
} as any)
const AuthenticatedTabsInventoryRoute =
  AuthenticatedTabsInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedTabsRouteRoute,
  } as any)
const AuthenticatedTabsSettingsRoute =
  AuthenticatedTabsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTabsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/signin': typeof SigninRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/enquiries': typeof AuthenticatedTabsEnquiriesRoute
  '/home': typeof AuthenticatedTabsHomeRoute
  '/inventory': typeof AuthenticatedTabsInventoryRoute
  '/settings': typeof AuthenticatedTabsSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/signin': typeof SigninRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/enquiries': typeof AuthenticatedTabsEnquiriesRoute
  '/home': typeof AuthenticatedTabsHomeRoute
  '/inventory': typeof AuthenticatedTabsInventoryRoute
  '/settings': typeof AuthenticatedTabsSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/design': typeof DesignRoute
  '/signin': typeof SigninRoute
  '/_authenticated/_tabs': typeof AuthenticatedTabsRouteRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/_tabs/enquiries': typeof AuthenticatedTabsEnquiriesRoute
  '/_authenticated/_tabs/home': typeof AuthenticatedTabsHomeRoute
  '/_authenticated/_tabs/inventory': typeof AuthenticatedTabsInventoryRoute
  '/_authenticated/_tabs/settings': typeof AuthenticatedTabsSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/signin'
    | '/notifications'
    | '/enquiries'
    | '/home'
    | '/inventory'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/signin'
    | '/notifications'
    | '/enquiries'
    | '/home'
    | '/inventory'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/design'
    | '/signin'
    | '/_authenticated/_tabs'
    | '/_authenticated/notifications'
    | '/_authenticated/_tabs/enquiries'
    | '/_authenticated/_tabs/home'
    | '/_authenticated/_tabs/inventory'
    | '/_authenticated/_tabs/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DesignRoute: typeof DesignRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_tabs': {
      id: '/_authenticated/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTabsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_tabs/enquiries': {
      id: '/_authenticated/_tabs/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AuthenticatedTabsEnquiriesRouteImport
      parentRoute: typeof AuthenticatedTabsRouteRoute
    }
    '/_authenticated/_tabs/home': {
      id: '/_authenticated/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedTabsHomeRouteImport
      parentRoute: typeof AuthenticatedTabsRouteRoute
    }
    '/_authenticated/_tabs/inventory': {
      id: '/_authenticated/_tabs/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedTabsInventoryRouteImport
      parentRoute: typeof AuthenticatedTabsRouteRoute
    }
    '/_authenticated/_tabs/settings': {
      id: '/_authenticated/_tabs/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedTabsSettingsRouteImport
      parentRoute: typeof AuthenticatedTabsRouteRoute
    }
  }
}

interface AuthenticatedTabsRouteRouteChildren {
  AuthenticatedTabsEnquiriesRoute: typeof AuthenticatedTabsEnquiriesRoute
  AuthenticatedTabsHomeRoute: typeof AuthenticatedTabsHomeRoute
  AuthenticatedTabsInventoryRoute: typeof AuthenticatedTabsInventoryRoute
  AuthenticatedTabsSettingsRoute: typeof AuthenticatedTabsSettingsRoute
}

const AuthenticatedTabsRouteRouteChildren: AuthenticatedTabsRouteRouteChildren =
  {
    AuthenticatedTabsEnquiriesRoute: AuthenticatedTabsEnquiriesRoute,
    AuthenticatedTabsHomeRoute: AuthenticatedTabsHomeRoute,
    AuthenticatedTabsInventoryRoute: AuthenticatedTabsInventoryRoute,
    AuthenticatedTabsSettingsRoute: AuthenticatedTabsSettingsRoute,
  }

const AuthenticatedTabsRouteRouteWithChildren =
  AuthenticatedTabsRouteRoute._addFileChildren(
    AuthenticatedTabsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTabsRouteRoute: typeof AuthenticatedTabsRouteRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTabsRouteRoute: AuthenticatedTabsRouteRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DesignRoute: DesignRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
